# Generated by Django 2.2.16 on 2022-07-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категории отзыва', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slugs', to='reviews.Categories', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Жанр отзыва', related_name='slugs', to='reviews.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='852HiLamgA', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
